# Data Visualisation - Group Project

## Airbnb Dataset

In [1]:
# First of all, we need to import pandas library
import pandas as pd

# Then we can try to read the CSV file for the first time
df = pd.read_csv('./Ireland Airbnb Listings (Ireland Airbnb Listings).csv')
df.info()
df.head(5)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31907 entries, 0 to 31906
Data columns (total 18 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              31907 non-null  int64
 1   name                            31907 non-null  object
 2   host_id                         31907 non-null  int64
 3   host_name                       30734 non-null  object
 4   neighbourhood_group             31907 non-null  object
 5   neighbourhood                   31907 non-null  object
 6   latitude                        31907 non-null  float64
 7   longitude                       31907 non-null  float64
 8   room_type                       31907 non-null  object
 9   price                           26181 non-null  float64
 10  minimum_nights                  31907 non-null  int64
 11  number_of_reviews               31907 non-null  int64
 12  last_review                     27692 non-null  object
 13  reviews_per_month               27692 non-null  float64
 14  calculated_host_listings_count  31907 non-null  int64
 15  availability_365                31907 non-null  int64
 16  number_of_reviews_ltm           31907 non-null  int64
 17  license                         0 non-null      float64
dtypes: float64(5), int64(7), object(6)
memory usage: 4.4+ MB

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
0,1218218173738460000,Riverside modern gem Dublin 2 bedrooms 2 bathr...,574242889,Krzysztof,Dublin City Council,Ballyfermot-Drimnagh LEA-5,53.34791,-6.345980,Entire home/apt,223.0,3,25,6/1/2025,2.47,2,160,25,NaN
1,1108584318776640000,Inchicore Soul(25 mins to city & airport),566164556,Jongeun,Dublin City Council,Ballyfermot-Drimnagh LEA-5,53.32875,-6.332817,Private room,80.0,2,43,10/27/2024,2.79,1,0,27,NaN
2,39202188,20 Min to centre (5km) / airport 30 min,103100241,Ed,Dublin City Council,Ballyfermot-Drimnagh LEA-5,53.33043,-6.333420,Private room,79.0,1,221,6/20/2025,3.22,5,122,29,NaN
3,571771563283545000,Modern 1 bedroom guest house with free parking,9871514,Mareesa And Evan,Dublin City Council,Ballyfermot-Drimnagh LEA-5,53.33843,-6.330380,Entire home/apt,115.0,1,231,6/17/2025,5.78,2,259,73,NaN
4,52965094,Cosy townhouse facing onto War Memorial Park,6515831,Elaine,Dublin City Council,Ballyfermot-Drimnagh LEA-5,53.34399,-6.329470,Private room,42.0,5,70,6/14/2025,1.58,2,21,15,NaN